version: "3"
services:
    php:
        build:
            context: .
            dockerfile: docker/php/php.dockerfile
        env_file:
        - web-variables.env
        external_links:
        - mysql_db_1:db
        networks:
        - default
        - mysql_default
        volumes:
        - form-sender-vendor-sync:/opt/vendor:nocopy
        - form-sender-node-sync:/opt/node_modules:nocopy
        - form-sender-app-sync:/opt:nocopy
        environment:
            XDEBUG_CONFIG: "remote_host=192.168.31.231"
            PHP_IDE_CONFIG: "serverName=docker"
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/nginx.dockerfile
        env_file:
        - web-variables.env
        external_links:
        - nginx-proxy_nginx-proxy_1:nginx-proxy
        links:
        - php
        depends_on:
        - php
        networks:
        - default
        - nginx-proxy_default
        expose:
        - 80
        volumes:
        - form-sender-vendor-sync:/opt/vendor:nocopy
        - form-sender-node-sync:/opt/node_modules:nocopy
        - form-sender-app-sync:/opt:nocopy
networks:
    mysql_default:
        external: true
    nginx-proxy_default:
        external: true
volumes:
    form-sender-vendor-sync:
        external: true
    form-sender-app-sync:
        external: true
    form-sender-node-sync:
        external: true
    mysql-data:
        external: true
